### ISSUE TITLE
Сконфигурировать порты

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.tech#1]
Сконфигурировать порты следующим образом:
1) :80 заглушка 404 (гличт)
2) :443 заглушка (гличт)

**Comment by DmitryUspensky** [comment]
[Блок](https://wallet.bitshares.eu/block/22015663) принятия в работу. 40 UTDEV.SKILL до 22.11.2017

**Comment by DmitryUspensky** [comment]
@kkrupovich проверяй
* http://transnet.tech
* https://transnet.tech

**Comment by cptn-solo** [comment]
Вроде все ок. закрываем

**Comment by cptn-solo** [comment]
BLOCK #22019489 uspenskydmitry1970 40UTDEV, спасибо!
