### ISSUE TITLE
Добавить CORS на сайт

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.tech#2]
Не получается дернуть метод с номером блока из API ajax запросом из-за отсутствия CORS

**Comment by ghost** [comment]
BLOCK #23555638
map-13
75UTDEV.SKILL
до середины 15.01.2018

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23555915

От | eugene-polyakov
Кому | utd-web
Количество | 30.00000 UTDEV.SKILL

до середины 15.01.2018

**Comment by EvgeniyPolyakov** [comment]
Задача решена, можно закрывать

**Comment by ghost** [comment]
[Добавил](https://github.com/u-transnet/Bitshares-admin-area/commit/4e210098b03cd9ec7933d771437d5242c7c3cab6)

**Comment by EvgeniyPolyakov** [comment]
остался баг в Safari: Blocked script execution in 'http://dev.transnet.tech/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

занимаюсь

**Comment by ghost** [comment]
API нужно перетащить на https просто так в лоб это не запилить за 1 минуту ибо API поднято не через nginx почему-то.

**Comment by ghost** [comment]
BLOCK #23590461
map-13
+75UTDEV.SKILL
до вечера 16.01.2018

**Comment by ghost** [comment]
@EvgeniyPolyakov пробуй и проверяй
Поднял через [uwsgi](https://github.com/u-transnet/Bitshares-admin-area/commit/ca697c6bc71d4cfb911cf87e8a5af717fb27ca4e) и завернул nginx на него из [/api](https://transnet.tech/api/)
Метод тут https://transnet.tech/api/get_current_block_num или тут http://transnet.tech/api/get_current_block_num если без https

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov просьба отписать о результатах

**Comment by EvgeniyPolyakov** [comment]
Некоторое время работало, видел, сейчас опять не приходит ничего с сервера во всех браузерах

**Comment by ghost** [comment]
Подвох с https в хроме был [тут](https://github.com/u-transnet/Bitshares-admin-area/commit/49ccdfcdd36257fdc6747a296c67225fdb9dcc75)

**Comment by EvgeniyPolyakov** [comment]
Добавление скилла на полдня

БЛОК #23651708

От | eugene-polyakov
Кому | utd-web
Количество | 30.00000 UTDEV.SKILL

**Comment by ghost** [comment]
BLOCK #23651810
map-13
+25UTDEV.SKILL
до вечера 18.01.2018
не работало из под https в chrome, коммент про подвох выше
total 175UTDEV.SKILL

**Comment by EvgeniyPolyakov** [comment]
@kkrupovich  Аллийлуйя. Можно закрывать

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23652341

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 175.00000 UTDEV

@EvgeniyPolyakov 
BLOCK #23652384

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 60.00000 UTDEV

Спасибо!
