### ISSUE TITLE
Добавить dev.transnet.tech на сертификат

### ISSUE THREAD

**Issue by ghost** [u-transnet/transnet.tech#3]
https://dev.transnet.tech должен открываться без предупреждений о проблемах с сертификатом безопасности

**Comment by ghost** [comment]
BLOCK #23567709
map-13
75UTDEV.SKILL
до середины 16.01.2018

**Comment by ghost** [comment]
@EvgeniyPolyakov 
https://dev.transnet.tech/

**Comment by ghost** [comment]
@kkrupovich 
Done

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23652806

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 75.00000 UTDEV
